# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Antonio Casto - Passionate iOS Developer"
description: >- # This means to ignore newlines until "baseurl:"
  "This is the personal website and blog of Antonio Casto - Passionate iOS Developer.
  Here you will find my projects, my thoughts and my contacts.""
lang: "en-EN"
url: "https://antoniocasto.github.io"   # Website base url (to be updated in the future to use personal domain)
baseurl: "" # The subpath of your site, e.g. /blog
permalink: "pretty" # Clean URLs (for instance, /about/ in place of /about.html)
markdown: kramdown
email: developer@acasto.dev
linkedin_link: https://www.linkedin.com/in/antonio-casto-547a411a1/
github_username:  antoniocasto

# Build settings
theme: null # Using personalized layout
plugins:
  - jekyll-seo-tag # Plugin for SEO meta tags
  - jekyll-sitemap # Plugin to generate sitemap.xml (useful for SEO and search engines)
collections:
  portfolio:
    output: true # Enables each markdown item in the collection to be output as a page

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
