# Site settings
title: "Antonio Casto - Passionate iOS Developer"
description: >-
  "This is the personal website and blog of Antonio Casto - Passionate iOS Developer.
  Here you will find my projects, my thoughts and my contacts."

# Multilingual settings
languages: ["en", "it"]  # Add new languages here (e.g., "fr", "de")
default_lang: "en"  # Default language

# Base URL settings
url: "https://acasto.dev"
baseurl: ""

# Permalinks - Clean and SEO-friendly URLs
permalink: "pretty"

# Social links
email: developer@acasto.dev
linkedin_link: https://www.linkedin.com/in/antonio-casto-547a411a1/
github_username: antoniocasto
github_link: https://github.com/antoniocasto/

# Build settings
markdown: kramdown
theme: null 
plugins:
  - jekyll-seo-tag  # Generates SEO meta tags
  - jekyll-sitemap  # Automatically generates sitemap.xml

# Collections - Portfolio and Blog
collections:
  portfolio:
    output: true
    permalink: "/:collection/:path/"
  posts:
    output: true
    permalink: "/:collection/:year/:month/:day/:title/"

# Default settings - Automatically assign the language based on the folder
# Default settings - Automatically assign the language based on the folder
defaults:
  # Regular pages (Home, About, Portfolio, etc.)
  - scope:
      path: "en"
      type: "pages"
    values:
      lang: "en"

  - scope:
      path: "it"
      type: "pages"
    values:
      lang: "it"

  # Blog posts (organized by language)
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: "en"
      permalink: "/en/blog/:year/:month/:day/:title/"

  - scope:
      path: "_posts/it"
      type: "posts"
    values:
      lang: "it"
      permalink: "/it/blog/:year/:month/:day/:title/"

  # Portfolio projects (organized by language)
  - scope:
      path: "_portfolio/en/*"
      type: "portfolio"
    values:
      lang: "en"
      permalink: "/en/portfolio/:path/"

  - scope:
      path: "_portfolio/it/*"
      type: "portfolio"
    values:
      lang: "it"
      permalink: "/it/portfolio/:path/"