name: Build and deploy Jekyll
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Deploy to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: gh-pages
          cname: acasto.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}